### ISSUE TITLE
Undefined symbol "author"

### ISSUE THREAD

**Issue by ghost** [Ilusion9/sourcecolors-inc-sm#1]
Compiler version -> SM 1.11 6911

// C:\Users\LAPTOP\Desktop\Compiler_6911\include\sourcecolors.inc(762) : error 017: undefined symbol "author"
// C:\Users\LAPTOP\Desktop\Compiler_6911\include\sourcecolors.inc(766) : error 017: undefined symbol "author"
// C:\Users\LAPTOP\Desktop\Compiler_6911\include\sourcecolors.inc(780) : error 017: undefined symbol "author"
// C:\Users\LAPTOP\Desktop\Compiler_6911\include\sourcecolors.inc(784) : error 017: undefined symbol "author"

**Comment by Ilusion9** [comment]
fixed
